<?php
/**
 * User roles for Vandrekalender.
 *
 * Registers the Event Organizer role — assigned automatically to every new
 * registration — and grants the custom event capabilities to administrators.
 * See docs/authentication.md.
 *
 * @package Vandrekalender
 */

defined( 'ABSPATH' ) || exit;

/**
 * Registers roles and event capabilities.
 *
 * Roles are persisted in the database, so this uses the same versioned-option
 * pattern as the rewrite-rules flush in the plugin bootstrap: bump
 * ROLES_VERSION whenever a role or capability changes, and the new definition
 * is applied once on the next request — locally and after a file-sync deploy,
 * with no activation hook or manual step.
 */
class Vandrekalender_Roles {

	/**
	 * Bump this whenever roles or capabilities below change.
	 */
	private const ROLES_VERSION = 1;

	/**
	 * Option storing the last applied roles version.
	 */
	private const VERSION_OPTION = 'vandrekalender_events_roles_version';

	/**
	 * Role slug for event organizers.
	 */
	public const EVENT_ORGANIZER = 'event_organizer';

	/**
	 * Every primitive capability generated by the event post type
	 * (capability_type => [ 'event', 'events' ] with map_meta_cap).
	 */
	private const ALL_EVENT_CAPS = [
		'edit_events',
		'edit_others_events',
		'edit_private_events',
		'edit_published_events',
		'publish_events',
		'read_private_events',
		'delete_events',
		'delete_others_events',
		'delete_private_events',
		'delete_published_events',
	];

	/**
	 * Constructor — registers hooks.
	 */
	public function __construct() {
		add_action( 'init', [ $this, 'maybe_setup_roles' ] );
		add_action( 'pre_get_posts', [ $this, 'restrict_event_list_to_own' ] );
		add_filter( 'map_meta_cap', [ $this, 'allow_reading_global_styles' ], 10, 4 );
		add_filter( 'map_meta_cap', [ $this, 'allow_editing_own_attachments' ], 10, 4 );
	}

	/**
	 * Let uploaders edit the attachments they uploaded.
	 *
	 * Attachments use capability_type 'post', and a parentless attachment
	 * reports its status as 'publish', so core maps editing one to
	 * edit_posts + edit_published_posts — blog-post capabilities the
	 * event_organizer role deliberately lacks. Without them the media modal
	 * renders alt text, title, caption and description read-only, so an
	 * organizer can upload a featured image but never describe it (an
	 * accessibility problem, not just an inconvenience). Scope is the user's
	 * own uploads; other people's media stay untouchable.
	 *
	 * @param string[] $caps    Primitive capabilities required.
	 * @param string   $cap     Requested meta capability.
	 * @param int      $user_id User being checked.
	 * @param array    $args    Context; $args[0] is the post ID.
	 * @return string[] Possibly remapped capabilities.
	 */
	public function allow_editing_own_attachments( array $caps, string $cap, int $user_id, array $args ): array {
		if ( 'edit_post' !== $cap || empty( $args[0] ) ) {
			return $caps;
		}

		$post = get_post( $args[0] );

		if ( ! $post || 'attachment' !== $post->post_type ) {
			return $caps;
		}

		if ( (int) $post->post_author !== $user_id ) {
			return $caps;
		}

		return [ 'upload_files' ];
	}

	/**
	 * Let event organizers read (not modify) global styles.
	 *
	 * Core maps reading the wp_global_styles post to the blog-posts
	 * capability edit_posts, which the event_organizer role deliberately
	 * lacks. Without read access the block editor cannot load the theme.json
	 * styling and renders events unstyled (browser-default fonts, no button
	 * styles, no spacing). Updating global styles still requires
	 * edit_theme_options.
	 *
	 * @param string[] $caps    Primitive capabilities required.
	 * @param string   $cap     Requested meta capability.
	 * @param int      $user_id User being checked.
	 * @param array    $args    Context; $args[0] is the post ID.
	 * @return string[] Possibly remapped capabilities.
	 */
	public function allow_reading_global_styles( array $caps, string $cap, int $user_id, array $args ): array {
		if ( 'read_post' !== $cap || empty( $args[0] ) ) {
			return $caps;
		}

		$post = get_post( $args[0] );

		if ( $post && 'wp_global_styles' === $post->post_type && user_can( $user_id, 'edit_events' ) ) {
			return [ 'edit_events' ];
		}

		return $caps;
	}

	/**
	 * Solo organizers see only their own events in the wp-admin list.
	 *
	 * Default WordPress shows other users' published posts in the admin list
	 * even without edit_others_events. Organization members will later get a
	 * shared list here instead (docs/authentication.md, post__in merge).
	 *
	 * @param \WP_Query $query The current query.
	 * @return void
	 */
	public function restrict_event_list_to_own( \WP_Query $query ): void {
		if ( ! is_admin() || ! $query->is_main_query() ) {
			return;
		}

		if ( \Vandrekalender\Event::CUSTOMPOSTTYPE !== $query->get( 'post_type' ) ) {
			return;
		}

		if ( current_user_can( 'edit_others_events' ) ) {
			return;
		}

		$query->set( 'author', get_current_user_id() );
	}

	/**
	 * Apply the role definitions once per ROLES_VERSION.
	 *
	 * @return void
	 */
	public function maybe_setup_roles(): void {
		if ( (int) get_option( self::VERSION_OPTION ) === self::ROLES_VERSION ) {
			return;
		}

		$this->setup_roles();
		update_option( self::VERSION_OPTION, self::ROLES_VERSION );
	}

	/**
	 * (Re)create the Event Organizer role, grant administrators all event
	 * capabilities, and make Event Organizer the default role for new users.
	 *
	 * @return void
	 */
	private function setup_roles(): void {
		// Remove first so capability changes apply on re-runs — add_role() is
		// a no-op when the role already exists.
		remove_role( self::EVENT_ORGANIZER );

		add_role(
			self::EVENT_ORGANIZER,
			__( 'Event Organizer', 'vandrekalender-events' ),
			[
				'read'                    => true,
				// Featured images.
				'upload_files'            => true,
				// Create events and edit their own; map_meta_cap blocks
				// editing others' events without edit_others_events.
				'edit_events'             => true,
				'edit_published_events'   => true,
				'publish_events'          => true,
				'delete_events'           => true,
				'delete_published_events' => true,
			]
		);

		$administrator = get_role( 'administrator' );

		if ( $administrator ) {
			foreach ( self::ALL_EVENT_CAPS as $capability ) {
				$administrator->add_cap( $capability );
			}
		}

		update_option( 'default_role', self::EVENT_ORGANIZER );
	}
}
