name: CI and CD (Nordicway Staging)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup-build-deploy-staging:
    uses: ./.github/workflows/deploy-to-nordicway.yml
    with:
      environment: staging
      ref: ${{ github.ref_name }}
    secrets: inherit
